pipeline:
  build:
    image: microsoft/dotnet:2.0.0-sdk
    when:
      event: push
    privileged: true
    commands:
    - dotnet --info
    - cd src/
    - dotnet restore
    - dotnet build    
    - dotnet publish -c Release -o ../docker-publish -v minimal
    - cd ../
    - cp Dockerfile docker-publish
  buid-docker: 
    image: docker:17.04.0-ce
    when:
      event: push
      branch: [master]
    privileged: true
    environment:
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login --username=registry --password=$REGISTRY_PASSWORD registry.fsilva.me
      - docker build -t registry.fsilva.me/shortener:1.0.${DRONE_BUILD_NUMBER} docker-publish
      - docker push registry.fsilva.me/shortener:1.0.${DRONE_BUILD_NUMBER}
    secrets: [ REGISTRY_PASSWORD ]

  apply-database-changes:
    image: microsoft/dotnet:2.0.0-sdk
    when:
      event: push
    privileged: true
    commands:
    - export ConnectionStrings__default=$STR_CON
    - echo $ConnectionStrings__default
    - cd src/
    - dotnet ef database update --configuration Release
  secrets: [ STR_CON ]
    
  deploy-containers: 
    image: docker:17.04.0-ce
    when:
      event: push
      branch: [master]
    environment:
    - IMAGE_VERSION=1.0.${DRONE_BUILD_NUMBER}
    - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export EXTERNAL_URL=https://s.fsilva.me/
      - export STR_CON=$STR_CON
      - docker image prune -af
      - docker login --username=registry --password=$REGISTRY_PASSWORD registry.fsilva.me
      - docker stack deploy --with-registry-auth -c stack.yml shortener
    secrets: [ REGISTRY_PASSWORD, STR_CON ]