version: '3'

services:
  mysql:
    image: mysql:8.0.0
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=shorteneruser
      - MYSQL_PASSWORD=shortenerpass