version: '3'

services:
  web:
    image: registry.fsilva.me/shortener:${IMAGE_VERSION}
    ports:
      - 5051:80
    networks:
      - mynet     
    environment:
    - ShortenerSettings__Url=${EXTERNAL_URL}
    - ConnectionStrings__default=${STR_CON} 
    deploy:
      placement:
        constraints:
          - node.labels.stack == app

networks:
  mynet:
    external: true